# Generated by Django 4.0.3 on 2022-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_complete_remove_item_text_item_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylist',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrylist',
            name='hometown',
            field=models.CharField(default='unlisted', max_length=200),
        ),
        migrations.AddField(
            model_name='dataentrylist',
            name='title',
            field=models.CharField(default='unlisted', max_length=200),
        ),
        migrations.AlterField(
            model_name='dataentrylist',
            name='name',
            field=models.CharField(default='unlisted', max_length=200),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
