# Generated by Django 4.0.3 on 2022-03-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dataentrylist_age_dataentrylist_hometown_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntryList',
            new_name='DataEntryItems',
        ),
    ]
